package talium;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import talium.inputSystem.HealthManager;
import talium.stringTemplates.Template;
import talium.stringTemplates.TemplateService;
import talium.twitch4J.TwitchUserPermission;
import talium.twitchCommands.cooldown.ChatCooldown;
import talium.twitchCommands.cooldown.CooldownType;
import talium.twitchCommands.persistence.CommandEntity;
import talium.twitchCommands.persistence.MessagePattern;
import talium.twitchCommands.persistence.TriggerService;
import talium.twitchCommands.triggerEngine.CommandWithCallbackCache;
import talium.twitchCommands.triggerEngine.TriggerCallback;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

/// Used as a central place to register actions and resources with parts of the bot
@Component
public class Registrar {

    private static TemplateService templateService;
    private static TriggerService triggerService;

    @Autowired
    public Registrar(TemplateService templateService, TriggerService triggerService) {
        Registrar.templateService = templateService;
        Registrar.triggerService = triggerService;
    }

    /// Register Custom HealthUI titel and description
    public static void registerHealthDescription(String self, String title, String description) {
        HealthManager.addCustomization(self, title, description);
    }

    /// Register Custom HealthUI titel and description
    public static void registerHealthDescription(Class<?> self, String title, String description) {
        HealthManager.addCustomization(self.getCanonicalName(), title, description);
    }

    public interface ResetableCache {
        void rebuild();
    }

    /// Register a function to reset/rebuild a application cache from the panel ui
    public static void registerResetableChache(String name, String description, ResetableCache cache) {
        //TODO register cache, show in ui, act on reset HTTP post
    }

    /// Register an autogenerated command with the bot
    public static class Command {
        //set all defaults
        String id;
        List<Pattern> regexPattern = new ArrayList<>();
        List<String> prefixPattern = new ArrayList<>();
        TwitchUserPermission permission = TwitchUserPermission.EVERYONE;
        ChatCooldown userCooldown = new ChatCooldown(CooldownType.MESSAGES, 0);
        ChatCooldown globalCooldown = new ChatCooldown(CooldownType.MESSAGES, 0);

        public Command(String id) {
            checkId(id);
            this.id = id;
        }

        public Command(String id, String prefixPattern) {
            checkId(id);
            this.id = id;
            this.prefixPattern.add(prefixPattern);
        }

        private static void checkId(String id) {
            if (id == null || id.isEmpty()) {
                throw new IllegalArgumentException("Command id cannot be null or empty");
            }
            if (id.startsWith("userCommand.")) {
                throw new IllegalArgumentException("Autogenerated command is not allowed to have the prefix \"userCommand.\" cause: '" + id);
            }
        }

        public Command id(String id) {
            checkId(id);
            this.id = id;
            return this;
        }

        public Command prefixPattern(String prefixPattern) {
            this.prefixPattern.add(prefixPattern);
            return this;
        }

        public Command regexPattern(String regexPattern) {
            this.regexPattern.add(Pattern.compile(regexPattern));
            return this;
        }

        public Command permission(TwitchUserPermission permission) {
            this.permission = permission;
            return this;
        }

        public Command userCooldown(ChatCooldown userCooldown) {
            this.userCooldown = userCooldown;
            return this;
        }

        public Command globalCooldown(ChatCooldown globalCooldown) {
            this.globalCooldown = globalCooldown;
            return this;
        }

        /// Registers an automatically generated command with a callback
        ///
        /// @return TriggerEntity that was saved to the DB
        public CommandEntity registerActionCommand(TriggerCallback callback) {
            var messagePatterns = new ArrayList<>(regexPattern.stream().map(pattern -> new MessagePattern(pattern.pattern(), true, false, true)).toList());
            messagePatterns.addAll(prefixPattern.stream().map(pattern -> new MessagePattern(pattern, false, false, true)).toList());
            CommandEntity entity = new CommandEntity(id, "", messagePatterns, permission, userCooldown, globalCooldown, true, null);
            var saved = triggerService.save(entity);
            CommandWithCallbackCache.upsertCallback(this.id, callback);
            return saved;
        }

        /// Registers an automatically generated command without a callback, but with a template
        ///
        /// @return TriggerEntity that was saved to the DB
        public CommandEntity registerTextCommand(String template) {
            return registerTextCommand(template, null);
        }

        /// Registers an automatically generated command without a callback, but with a template
        ///
        /// @return TriggerEntity that was saved to the DB
        public CommandEntity registerTextCommand(String template, String messageColor) {
            templateService.saveIfAbsent(new Template(id, template, messageColor));
            var messagePatterns = new ArrayList<>(regexPattern.stream().map(pattern -> new MessagePattern(pattern.pattern(), true, false, true)).toList());
            messagePatterns.addAll(prefixPattern.stream().map(pattern -> new MessagePattern(pattern, false, false, true)).toList());
            CommandEntity entity = new CommandEntity(id, "", messagePatterns, permission, userCooldown, globalCooldown, true, null);
            var saved = triggerService.save(entity);
            CommandWithCallbackCache.upsertCommand(saved);
            return saved;
        }

        public static void upsert(CommandEntity entity) {
            var saved = triggerService.save(entity);
            CommandWithCallbackCache.upsertCommand(saved);
        }

        /**
         * Deletes the command with the ID and unregisters it from the commandEngine
         * @param commandId id of command to delete
         */
        public static void delete(String commandId) {
            triggerService.delete(commandId);
            CommandWithCallbackCache.unloadCommand(commandId);
        }
    }

    /// Registers a template with the context variables (captured environment)
    public static Template registerTemplate(Template template) {
        return templateService.saveIfAbsent(template);
    }

    /// Registers a template with the context variables (captured environment)
    public static Template registerTemplate(String templateId, String template, String messageColor) {
        return templateService.saveIfAbsent(new Template(templateId, template, messageColor));
    }

    /// Registers a template with the context variables (captured environment)
    public static Template registerTemplate(String templateId, String template) {
        return templateService.saveIfAbsent(new Template(templateId, template, null));
    }
}
