package talium.twitchCommands.persistence;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import talium.stringTemplates.TemplateService;

import java.util.List;
import java.util.Optional;


@Service
public class TriggerService {
    private final TriggerRepo repo;
    private final TemplateService templateService;
    private final MessagePatternRepo messagePatternRepo;

    @Autowired
    public TriggerService(TriggerRepo triggerRepo, TemplateService templateService, MessagePatternRepo messagePatternRepo) {
        this.repo = triggerRepo;
        this.templateService = templateService;
        this.messagePatternRepo = messagePatternRepo;
    }

    @Transactional
    public CommandEntity save(CommandEntity entity) {
        var oldEntity = repo.findById(entity.id);

        for (MessagePattern pattern : entity.patterns) {
            pattern.parentTrigger = entity;
        }
        if (entity.template != null && entity.template.id != null && !entity.template.id.isBlank()) {
            templateService.save(entity.template);
        }
        var saved = repo.save(entity);
        oldEntity.ifPresent(messagePatternRepo::deleteAllByParentTrigger);
        return saved;
    }

    public List<CommandEntity> getAllUserTriggers() {
        return repo.getAllByisAutoGenerated(false);
    }

    public List<CommandEntity> searchUserBy(String search) {
        var ids = repo.searchAllUserBy(search);
        return repo.findAllById(ids);
    }

    public List<CommandEntity> getAllTriggers() {
        return repo.findAll();
    }

    public List<CommandEntity> searchBy(String search) {
        var ids = repo.searchAllBy(search);
        return repo.findAllById(ids);
    }

    public Optional<CommandEntity> getTriggersId(String id) {
        return repo.findById(id);
    }

    public void delete(String id) {
        repo.deleteById(id);
    }


    public void setEnabled(CommandEntity trigger, boolean enabled) {
        for (MessagePattern pattern : trigger.patterns) {
            pattern.isEnabled = enabled;
        }
        repo.save(trigger);
    }

    public void setVisible(CommandEntity trigger, boolean visible) {
        for (MessagePattern pattern : trigger.patterns) {
            pattern.isVisible = visible;
        }
        repo.save(trigger);
    }
}
