name: Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean compile
        working-directory: bot
        env:
          JAVA_TOOL_OPTIONS: --enable-preview
      - name: Run all Tests
        run: mvn test
        working-directory: bot
        env:
          JAVA_TOOL_OPTIONS: --enable-preview
